<?php
require_once '../includes/dbconnection.php'; require_once '../includes/session.php';
$page='result'; $pageTitle='Grading guide'; $pageEyebrow='Academic standards'; $pageDescription='Understand how scores translate into grade points and diploma classifications.'; require 'includes/layoutTop.php';
$grades=[['75–100','AA','4.00'],['70–74','A','3.50'],['65–69','AB','3.25'],['60–64','B','3.00'],['55–59','BC','2.75'],['50–54','C','2.50'],['45–49','CD','2.25'],['40–44','D','2.00'],['0–39','F','0.00']];
$classes=[['Distinction','3.50 and above'],['Upper Credit','3.00–3.49'],['Lower Credit','2.50–2.99'],['Pass','2.00–2.49'],['Fail','Below 2.00']];
?>
<section class="portal-card"><div class="portal-card-title"><div><h2>Diploma classification</h2><p>Your CGPA determines the final classification of your programme.</p></div><a class="portal-button secondary" href="printGradingCriteria.php" target="_blank"><i class="fa fa-print"></i> Print guide</a></div><div class="grade-scale"><?php foreach($classes as $item): ?><div class="grade-band"><strong><?php echo htmlspecialchars($item[1]); ?></strong><span><?php echo htmlspecialchars($item[0]); ?></span><small>Cumulative GPA</small></div><?php endforeach; ?></div></section>
<section class="portal-card" style="margin-top:20px"><div class="portal-card-title"><div><h2>Score conversion</h2><p>Each course score maps to a letter grade and grade point.</p></div></div><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Score range</th><th>Letter grade</th><th>Grade point</th><th>Outcome</th></tr></thead><tbody><?php foreach($grades as $grade): $failed=$grade[1]==='F'; ?><tr><td><strong><?php echo htmlspecialchars($grade[0]); ?></strong></td><td><span class="portal-badge <?php echo $failed?'danger':''; ?>"><?php echo htmlspecialchars($grade[1]); ?></span></td><td><?php echo htmlspecialchars($grade[2]); ?></td><td><?php echo $failed?'No credit earned':'Credit earned'; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require 'includes/layoutBottom.php'; ?>
