<?php
require_once '../includes/dbconnection.php'; require_once '../includes/session.php';
if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32));
$message=''; $messageType='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $token=(string)($_POST['csrf_token']??'');
    if(!hash_equals($_SESSION['csrf_token'],$token)){ $message='Your session expired. Refresh the page and try again.'; $messageType='error'; }
    elseif(!empty($_SESSION['temporary_login'])){ $message='Profile changes are disabled during a temporary preview session.'; $messageType='error'; }
    else{
        $firstName=trim((string)($_POST['firstName']??'')); $lastName=trim((string)($_POST['lastName']??'')); $otherName=trim((string)($_POST['otherName']??''));
        if($firstName===''||$lastName===''){ $message='First name and last name are required.'; $messageType='error'; }
        elseif(strlen($firstName)>80||strlen($lastName)>80||strlen($otherName)>80){ $message='Names must be 80 characters or fewer.'; $messageType='error'; }
        else{ $stmt=mysqli_prepare($conn,'UPDATE tblstudent SET firstName=?,lastName=?,otherName=? WHERE matricNo=?'); mysqli_stmt_bind_param($stmt,'ssss',$firstName,$lastName,$otherName,$matricNo); if(mysqli_stmt_execute($stmt)){$_SESSION['firstName']=$firstName;$_SESSION['lastName']=$lastName;$message='Your profile was updated successfully.';$messageType='success';}else{$message='We could not update your profile right now.';$messageType='error';} }
    }
}
$stmt=mysqli_prepare($conn,'SELECT s.firstName,s.lastName,s.otherName,s.matricNo,l.levelName,f.facultyName,d.departmentName,se.sessionName FROM tblstudent s LEFT JOIN tbllevel l ON l.Id=s.levelId LEFT JOIN tblfaculty f ON f.Id=s.facultyId LEFT JOIN tbldepartment d ON d.Id=s.departmentId LEFT JOIN tblsession se ON se.Id=s.sessionId WHERE s.matricNo=? LIMIT 1'); mysqli_stmt_bind_param($stmt,'s',$matricNo);mysqli_stmt_execute($stmt);$profile=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt))?:[];
$page='profile';$pageTitle='My profile';$pageEyebrow='Account';$pageDescription='Review your academic identity and maintain your personal name details.';require 'includes/layoutTop.php';
$initials=strtoupper(substr($profile['firstName']??'S',0,1).substr($profile['lastName']??'',0,1));
?>
<div class="profile-grid"><aside class="portal-card profile-identity"><div class="profile-avatar"><?php echo htmlspecialchars($initials); ?></div><h2 style="font-size:20px;margin:0"><?php echo htmlspecialchars(trim(($profile['firstName']??'').' '.($profile['lastName']??''))); ?></h2><p style="color:#6b788b"><?php echo htmlspecialchars($profile['matricNo']??''); ?></p><div class="profile-meta"><div><span>Department</span><strong><?php echo htmlspecialchars($profile['departmentName']??'Not assigned'); ?></strong></div><div><span>Faculty</span><strong><?php echo htmlspecialchars($profile['facultyName']??'Not assigned'); ?></strong></div><div><span>Level</span><strong><?php echo htmlspecialchars($profile['levelName']??'Not assigned'); ?></strong></div><div><span>Academic session</span><strong><?php echo htmlspecialchars($profile['sessionName']??'Not assigned'); ?></strong></div></div></aside>
<section class="portal-card"><div class="portal-card-title"><div><h2>Personal details</h2><p>Your matric number and academic assignments are managed by the institution.</p></div></div><?php if($message): ?><div class="portal-alert <?php echo $messageType; ?>"><?php echo htmlspecialchars($message); ?></div><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($_SESSION['csrf_token']); ?>"><div class="portal-form-grid"><div class="portal-field"><label for="firstName">First name</label><input id="firstName" name="firstName" value="<?php echo htmlspecialchars($profile['firstName']??''); ?>" maxlength="80" required <?php echo !empty($_SESSION['temporary_login'])?'disabled':''; ?>></div><div class="portal-field"><label for="lastName">Last name</label><input id="lastName" name="lastName" value="<?php echo htmlspecialchars($profile['lastName']??''); ?>" maxlength="80" required <?php echo !empty($_SESSION['temporary_login'])?'disabled':''; ?>></div><div class="portal-field full"><label for="otherName">Other name <span style="font-weight:400;color:#8793a2">(optional)</span></label><input id="otherName" name="otherName" value="<?php echo htmlspecialchars($profile['otherName']??''); ?>" maxlength="80" <?php echo !empty($_SESSION['temporary_login'])?'disabled':''; ?>></div><div class="full"><button class="portal-button" type="submit" <?php echo !empty($_SESSION['temporary_login'])?'disabled':''; ?>><i class="fa fa-check"></i> Save changes</button></div></div></form></section></div>
<?php require 'includes/layoutBottom.php'; ?>
