<?php
require_once '../includes/dbconnection.php'; require_once '../includes/session.php';
$stmt=mysqli_prepare($conn,'SELECT s.firstName,s.lastName,s.otherName,s.matricNo,f.facultyName,d.departmentName,c.cgpa,c.classOfDiploma FROM tblstudent s LEFT JOIN tblfaculty f ON f.Id=s.facultyId LEFT JOIN tbldepartment d ON d.Id=s.departmentId LEFT JOIN tblcgparesult c ON c.matricNo=s.matricNo WHERE s.matricNo=? LIMIT 1');
mysqli_stmt_bind_param($stmt,'s',$matricNo); mysqli_stmt_execute($stmt); $record=mysqli_fetch_assoc(mysqli_stmt_get_result($stmt))?:[];
$stmt=mysqli_prepare($conn,'SELECT fr.gpa,fr.classOfDiploma,fr.totalCourseUnit,l.levelName,se.semesterName,ss.sessionName FROM tblfinalresult fr LEFT JOIN tbllevel l ON l.Id=fr.levelId LEFT JOIN tblsemester se ON se.Id=fr.semesterId LEFT JOIN tblsession ss ON ss.Id=fr.sessionId WHERE fr.matricNo=? ORDER BY fr.sessionId,fr.levelId,fr.semesterId');
mysqli_stmt_bind_param($stmt,'s',$matricNo); mysqli_stmt_execute($stmt); $history=[]; $result=mysqli_stmt_get_result($stmt); while($row=mysqli_fetch_assoc($result))$history[]=$row;
$page='result'; $pageTitle='Final academic standing'; $pageEyebrow='Performance'; $pageDescription='Your cumulative result and semester-by-semester progression.'; require 'includes/layoutTop.php';
$cgpa=$record['cgpa'] ?? null; $classification=$record['classOfDiploma'] ?? 'Not yet available';
?>
<?php if($cgpa!==null): ?><section class="standing-hero"><div class="standing-score"><div><strong><?php echo number_format((float)$cgpa,2); ?></strong><span>Cumulative GPA</span></div></div><div><p class="eyebrow" style="color:#79e2c2">Current classification</p><h2><?php echo htmlspecialchars($classification); ?></h2><p><?php echo htmlspecialchars(trim(($record['firstName']??'').' '.($record['lastName']??''))); ?> &middot; <?php echo htmlspecialchars($record['matricNo']??''); ?><br><?php echo htmlspecialchars($record['departmentName']??''); ?>, <?php echo htmlspecialchars($record['facultyName']??''); ?></p></div></section>
<?php else: ?><section class="portal-card"><div class="portal-empty"><i class="fa fa-hourglass-half"></i><strong>Cumulative result pending</strong><span>Your final academic standing has not been published yet.</span></div></section><?php endif; ?>

<section class="portal-card" style="margin-top:20px"><div class="portal-card-title"><div><h2>Academic progression</h2><p>A historical view of your semester outcomes.</p></div></div>
<?php if(!$history): ?><div class="portal-empty"><i class="fa fa-line-chart"></i><strong>No progression data</strong><span>Published semester summaries will appear here.</span></div><?php else: ?><div class="portal-table-wrap"><table class="portal-table"><thead><tr><th>Session</th><th>Level</th><th>Semester</th><th>Units</th><th>GPA</th><th>Standing</th></tr></thead><tbody><?php foreach($history as $row): ?><tr><td><?php echo htmlspecialchars($row['sessionName']??'—'); ?></td><td><?php echo htmlspecialchars($row['levelName']??'—'); ?></td><td><?php echo htmlspecialchars($row['semesterName']??'—'); ?></td><td><?php echo htmlspecialchars($row['totalCourseUnit']); ?></td><td><span class="portal-code"><?php echo number_format((float)$row['gpa'],2); ?></span></td><td><span class="portal-badge <?php echo $row['classOfDiploma']==='Fail'?'danger':''; ?>"><?php echo htmlspecialchars($row['classOfDiploma']); ?></span></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php require 'includes/layoutBottom.php'; ?>
